### ISSUE TITLE
cannot check obelisk parrot or ticket machine

### ISSUE THREAD

**Issue by shdadowking** [agilbert1412/StardewArchipelago#42]
it is impossible to check the ticket machine after getting boat repair, and you can't check farm obelisk parrot after getting the farm obelisk.

**Comment by agilbert1412** [comment]
Neither of these are true.
For the ticket machine, you must hold the battery packs for it to give you the repair prompt (since it's the same interaction tile, I had to make the game distinguish your intention in this way)
For the farm obelisk parrot, it is actually sitting one tile in front of the obelisk, so if you **don't** stand too close you can buy it.
