### ISSUE TITLE
Coffee shows archipelago icon when not needed

### ISSUE THREAD

**Issue by GFreak01** [agilbert1412/StardewArchipelago#55]
My game currently has "Coffee Bean" set for "Harvest" and "Shipsanity".   However, the coffee in my inventory shows the archipelago icon, as if it were necessary to ship.  (The hover text says "Harvest Coffee Bean, Shipsanity: Coffee Bean")

I assume the "Coffee" is pulling the icon status from "Coffee beans" due to the names being so similar.

**Comment by agilbert1412** [comment]
It is indeed due to names, as the matching for these icons is very crude. It's basically just "check if the text is contained within the location name", with a bit of fluff like exceptions.

But this case is an item that is indirectly related, but related nonetheless, and these, we have decided to keep them as they might be useful to someone (ex: deciding not to brew your next batch and ship some instead)
