### ISSUE TITLE
Error Sequence contains no elements - Craftsanity

### ISSUE THREAD

**Issue by GFreak01** [agilbert1412/StardewArchipelago#58]
As soon as I connect to the server with a new character, I get a looping error that breaks the game. "Sequence contains no elements"

See attached txt file for error from SMAPI console, as well as yaml file.

[Nyxx.yaml.txt](https://github.com/user-attachments/files/15541481/Nyxx.yaml.txt)
[error.txt](https://github.com/user-attachments/files/15541482/error.txt)

**Comment by GFreak01** [comment]
Through making some changes to the Stardrew options page, it looks like the issue is tied to Craftsanity.

Once that option is enabled, after I create a character and connect to the server.  As soon as I open my inventory the game lags and then I am no longer able to open the inventory.  Additionally, the SMAPI console outputs all the error text.

**Comment by agilbert1412** [comment]
This is a known issue that relates to using a controller.

In short, the vanilla game cannot handle a controller + an empty crafting page. In vanilla, the bug is present, but it never shows, because you start with some recipes. In Archipelago, without recipes, the bug now is visible.

Since this is a vanilla bug, I can't do much about it, but I'll keep the issue open because I am considering some funky patches to try to get around it.

In the meantime, here are your options:
1: Play on a keyboard until you get at least one recipe
2: Play without craftsanity if you want your controller
3: Cheat in a recipe using either the start_inventory, or a server command, to start with at least one (Suggested: Torch Recipe, because it doesn't unlock anything and won't break logic)

**Comment by GFreak01** [comment]
Thank you!
Adding the following line to the yaml, after death link, fixed the issue:
start_inventory: {'Chest Recipe': 1}

**Comment by agilbert1412** [comment]
By the way, I recommend you join the archipelago Discord. There isw a channel dedicated to Stardew, where many people (in addition to myself) will be able to help, probably faster, if you have questions or problems :)

**Comment by agilbert1412** [comment]
Fixed in https://github.com/agilbert1412/StardewArchipelago/releases/tag/5.5.3
